# Generated by Django 4.2.5 on 2023-09-27 09:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(max_length=125)),
                ('section_1_title', models.CharField(max_length=250)),
                ('section_1_desc', wagtail.fields.RichTextField()),
                ('section_1_call_to_action', models.CharField(blank=True, max_length=50, null=True)),
                ('section_1_call_to_action_path', models.CharField(blank=True, max_length=25, null=True)),
                ('section_2_title', models.CharField(max_length=250)),
                ('section_2_desc', wagtail.fields.RichTextField()),
                ('section_2_call_to_action', models.CharField(blank=True, max_length=50, null=True)),
                ('section_2_call_to_action_path', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blockquote_text',
            field=models.CharField(default='Project blockquote', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(default='Project name', max_length=125),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_call_to_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_call_to_action_path',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_text',
            field=models.CharField(default='Section text', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_title',
            field=models.CharField(default='Section title', max_length=125),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tile_1_header',
            field=models.CharField(default='Tile 1 header', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tile_2_header',
            field=models.CharField(default='Tile 2 header', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tile_3_header',
            field=models.CharField(default='Tile 3 header', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tile_4_header',
            field=models.CharField(default='Tile 4 header', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tile_5_header',
            field=models.CharField(default='Tile 5 header', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tiles_call_to_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tiles_call_to_action_path',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
