# Generated by Django 4.2.5 on 2024-11-18 17:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0004_workshoppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppage',
            name='body',
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='desc',
            field=models.CharField(blank=True, help_text='Short description or tagline for the workshop.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed description of the workshop.', null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='feedback',
            field=wagtail.fields.RichTextField(blank=True, help_text='Add feedback or testimonials from workshop participants.', null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='feedback_title',
            field=models.CharField(blank=True, help_text='Title for the feedback section.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='highlight_images',
            field=models.ManyToManyField(blank=True, help_text='Upload multiple images to create a collage for the highlights.', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='highlight_title',
            field=models.CharField(blank=True, help_text='Title for the highlights section.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='takeaways',
            field=wagtail.fields.RichTextField(blank=True, help_text='Key points or takeaways from the workshop.', null=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='takeaways_title',
            field=models.CharField(blank=True, help_text='Title for the key takeaways section.', max_length=150, null=True),
        ),
    ]
